# Site settings
title: CDC Influenza Division Bioinformatics Workshop
name: Bioinformatics Workshop
description: Training materials for a bioinformatics workshop developed by the United States' Centers for Disease Control and Prevention's Influenza Division in collaboration with the Association of Public Health Laboratories.
url: "https://cdcgov.github.io"   # production org Pages root
baseurl: "/id-bioifx-workshop"     # project repo name (keep if this is NOT cdcgov.github.io repo)

# Build settings
theme: minima
markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections (optional future expansion)
# collections:
#   lessons:
#     output: true
#     permalink: /lessons/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - extras/resources.md
  - vendor

# Keep site deterministic
future: false