# Site settings
title: CDC Influenza Division Bioinformatics Workshop
name: Influenza Bioinformatics Workshop
site_title: CDC Influenza Bioinformatics Workshop
topnav_title: Influenza Bioinformatics Workshop
description: Training materials for a bioinformatics workshop developed by the United States' Centers for Disease Control and Prevention's Influenza Division in collaboration with the Association of Public Health Laboratories.
company_name: US CDC Influenza Division
url: "https://cdcgov.github.io"   # production org Pages root
baseurl: "/id-bioifx-workshop"     # project repo name (keep if this is NOT cdcgov.github.io repo)

# SEO settings
lang: en
locale: en_US
author: CDC Influenza Division
tagline: Bioinformatics Training for Public Health Laboratories
logo: /assets/images/favicon.ico
social:
  name: CDC Influenza Division
  links:
    - https://github.com/cdcgov/id-bioifx-workshop

twitter:
  card: summary

output: web

github_editme_path: cdcgov/id-bioifx-workshop/blob/main/

feedback_disable: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections (optional future expansion)
collections:
  workshops:
    output: true
    permalink: /workshops/:name/
  tooltips:
    output: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: workshop_sidebar
      topnav: topnav
  - scope:
      path: "lessons"
      type: "pages"
    values:
      layout: "page"
      comments: false
      search: true
      sidebar: workshop_sidebar
      topnav: topnav
  - scope:
      path: ""
      type: workshops
    values:
      layout: page
      sidebar: workshop_sidebar
      topnav: topnav

sidebars:
  - workshop_sidebar

exclude:
  - .idea/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - extras/resources.md
  - vendor
  - scripts
  - __pycache__
  - WIP/genome_report/genome_report.qmd

# Keep site deterministic
future: false